export const REFRESH_STATE = "REFRESH_STATE";

export const AUTH_LOGIN = "AUTH_LOGIN";

export const AUTH_REGISTER= "AUTH_REGISTER";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_ATTEMPT = "AUTH_ATTEMPT";

export const UPDATE_SESSION_TIMEOUT = "UPDATE_SESSION_TIMEOUT";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";